### ISSUE TITLE
Cannot find on Obsidian Community Plugin list.

### ISSUE THREAD

**Issue by zzzgithubzzz** [Kageetai/obsidian-plugin-journal-review#1]

**Comment by Kageetai** [comment]
First thanks for your interest in my first little Obsidian plugin.

[My pull request](https://github.com/obsidianmd/obsidian-releases/pull/1733) to add this plugin to the list of official community plugins is still in review and will hopefully be available soon.

**Comment by Kageetai** [comment]
Closed as it's not merged and listed
