### ISSUE TITLE
Recurring option doesn't do anything

### ISSUE THREAD

**Issue by joshuarudd** [Kageetai/obsidian-plugin-journal-review#11]
I love that we can now set recurring timespans, like every year, but I've noticed that it doesn't seem to work. Here's what my settings look like, but it will only show posts from last year—not years prior on the same day of the year.

![20231231090604 2023-12-31 - Notes - Obsidian v1 5 3@2x](https://github.com/Kageetai/obsidian-plugin-journal-review/assets/23268/186467d0-d333-4b81-9748-a04614a83081)

**Comment by Kageetai** [comment]
Hey, that's odd, it should work with all notes from the daily notes/periodic notes settings. Can you try to show me your folder structure for your daily notes (without any content)?

**Comment by Kageetai** [comment]
Hey, I investigated the issue and just found a bug collection the older notes, so can you try to update to version `2.1.0`?!

**Comment by joshuarudd** [comment]
@Kageetai yes, it works! Sorry for not getting back to you with the details you requested. Thank you for fixing the issue!

**Comment by Kageetai** [comment]
Sure thing, I stumbled upon the solution because I noticed it wasn't working on my mobile device either, but perfectly fie on desktop.
Glad it works now
