### ISSUE TITLE
Showing duplicate entries

### ISSUE THREAD

**Issue by kosmic7** [Kageetai/obsidian-plugin-journal-review#13]
First off, I LOVE this plugin. It's so cool to be able to see notes from previous months/years each day. I do have a couple of issues though:

1. If I change the time span to 1 month, it will show a yearly entry twice. I assume it's returning it as a 12-month match and a 1-year match. Any way you can make it ignore duplicates?

2. This is not hugely important, but... if I only have monthly entries, it still says "a year ago:" at the top.

Thanks for creating this. It is awesomely useful!

**Comment by kosmic7** [comment]
Hey this wasn't a problem today, just FYI. Didn't want you to waste time on this for no reason. Will let you know if it happens again and if I can find a pattern to it. I'll close this in a few days if it's working OK.

![image](https://github.com/Kageetai/obsidian-plugin-journal-review/assets/8209593/cdce6f20-10a5-4e6a-ac0b-bc5f9967817b)

**Comment by Kageetai** [comment]
Hey there,
sorry for the late reply. Glad you like my plugin though, hearing this always motivates to keep improving it. :)
Regarding your two points:

1. Can you show me your settings for the plugin you are using? I am thinking if you have a "recurring 1 month" and "1 year" setting, these are kind of overlapping, as in "every month" will automatically also match for "12 months/1 year", therefore the duplicates. For this case at least you could just remove the "1 year" setting, that I assume you have. There are some other cases where two settings only partially overlap, so I can look into preventing duplicates then.
2. What would you think it should say there at the top? I am just using Obsidians internal date formatting library, to format the difference between now and the note in a human-readable format, therefore it says "a year ago"

**Comment by Kageetai** [comment]
The duplicate entries are fixed in version 2.5.0. Let me know if that works for you
