### ISSUE TITLE
Preview length setting not saving

### ISSUE THREAD

**Issue by tariquesani** [Kageetai/obsidian-plugin-journal-review#141]
Seems like I have encountered a bug. The preview length setting seems to not save. When I change it, it seems to take effect but when I open the vault next it defaults back to 100

**Comment by Kageetai** [comment]
Sorry for the late reply.
I checked on that bug and indeed, there is some problem with the rerender delay, when setting it to a lower number. I will try to make a fix at some point, but relatively busy these days.

**Comment by Kageetai** [comment]
Thanks for the bug report, managed to figure it out, even though it seems a somewhat weird behaviour/bug how the internal Obsidian sliders behave.
Should be fixed in version [2.4.4](https://github.com/Kageetai/obsidian-plugin-journal-review/releases/tag/2.4.4)
