### ISSUE TITLE
Not working with filenames containing text after the date

### ISSUE THREAD

**Issue by jorgesanchezurien** [Kageetai/obsidian-plugin-journal-review#6]
Figured out an easy solution with a simple modification in the plugin source code:

edit main.js under .obsidian/plugins/journal-review
locate the following line in funtion getDateFromFilename(file, granularity)
`const noteDate = window.moment(filename, format, true);`
change the last argument "true" to "false" to disable strict parsing: https://momentjs.com/guides/#/parsing/strict-mode/

**Comment by Kageetai** [comment]
Hello and thanks for using my simple plugin :)

Unfortunately, the piece of code you are referring to is not part of my plugin itself, but another library used to access the daily notes.
Therefore, I cannot directly implement this feature here, but would have to adjust said library.
Can you also give an example how you have configured your daily notes to work with text after the dates? I quickly tried this with my current setup with the periodic notes plugin, but this doesn't seem to work for me, as there seems to be no way to configure the note format to include other arbitrary texts. How did you configure your daily notes for that?

**Comment by jorgesanchezurien** [comment]
Hello and thanks for your reply.

My Daily Notes date format is configured with the default "YYYY-MM-DD" but
I like to add a title after the date to my notes, like this "2023-06-12
Beach day". Since the resulting filename doesn't strictly match the format,
these notes are not taken into account, but with the proposed change they
are.

It would be nice to have support for these types of notes somehow in your
plugin.
Thank you.

**Comment by Kageetai** [comment]
Hmm, out of curiosity, with your current configuration, does it still open the same note after adding a name to it, when you click "open today" or so?
I mean for me when I try that, add a name to my daily note today, and then use the command "open daily note", it creates a new note, instead of reopening the note I just edited before.

I can look into supporting that, but I think it might not be entirely possible, as I am just using the same configuration the core daily note plugin is using to create and open notes.

**Comment by jorgesanchezurien** [comment]
Yes, you're right. The core Daily Notes plugin doesn't take into account these notes which do not strictly match the configured date format. 
The thing is that I'm using the Calendar community plugin with the same behavior by default but I've done the same proposed change in the call to the moment() function to make it work. See https://github.com/liamcain/obsidian-calendar-plugin/discussions/90#discussioncomment-6144763

**Comment by Kageetai** [comment]
I see, this same solution has the same problem as here for me, you are not adjusting the calendar plugin itself, but the code from the library it uses to fetch the daily notes. Therefore we cannot fix this on our side (me or the developer of the calendar plugin), but it needs to be fixed on with that underlying library [here](https://github.com/liamcain/obsidian-daily-notes-interface/blob/a9d90f207705d9360b8b57e6dbc3ffbe7493c915/src/parse.ts#L74).
You can bring this up to that repo over there. But maybe that developer had a reason to use the strict mode.

**Comment by jorgesanchezurien** [comment]
Well it looks like the library you mentioned is developed by the same author than the Calendar plugin. I guess he could parameterize the call to the parsing function to be strict or not, based on a plugin setting... Although this wouldn't fix the core "open daily note" functionality, the Calendar and Journal Review would support non-strict daily notes filenames.
Just an idea...
Thanks

**Comment by Kageetai** [comment]
Yes, making this somewhat adjustable via plugin settings would be ideal. You can suggest this to the developer of these plugins.
From the same person is also the [Period Notes plugin](https://github.com/liamcain/obsidian-periodic-notes), which I am currently using instead of the core plugin, maybe this can just be fixed there for all places then.

**Comment by jorgesanchezurien** [comment]
Feature requested in the underlying library: https://github.com/liamcain/obsidian-daily-notes-interface/issues/27

**Comment by Kageetai** [comment]
Awesome, thanks for that. Whenever that might be merged, I can adjust settings on my plugin if needed.
