### ISSUE TITLE
Display reviews based on the journal file open

### ISSUE THREAD

**Issue by tomzx** [Kageetai/obsidian-plugin-journal-review#66]
Hello! Thanks a lot for your plugin, it is exactly what I wanted to have when I write my own daily journal.

One thing I'd find very useful is the ability for the review/look back to be based on the date of the note currently open.

As of now, if it's 2024/04/23, if the plugin is configured to show yesterday's note, yesterday's note will show 2024/04/22, regardless of the note open. If I open my note for 2024/04/15, I'd like to see the review for 2024/04/14, not 2024/04/22.

This would enable viewing a journal entry with its associated entries in the past instead of only based on today's date.

**Comment by Kageetai** [comment]
Hi there,
glad to hear the plugin is of use to someone. And I am always happy to listen to ideas and further improvements.

I already had the same idea as you and thought it would be nice to switch between days to look, either based on the open note or with a day switcher. Open note might actually be easier, so should just get to that again, now that I know others would like to see that as well

**Comment by fzadow** [comment]
I'd love you even more for this feature. Would be great to browse through my journal and always have the review view update.

**Comment by Kageetai** [comment]
Hey there,
thanks for the comment. I had slept a bit on this plugin, but seeing people interested always motivates me, so I took another look into this and it was actually not too tricky, apart from some other refactoring.
I just released a version [2.4.0](https://github.com/Kageetai/obsidian-plugin-journal-review/releases/tag/2.4.0) with a new setting `Date based on selected note`.
Please install this version and let me know if this works as expected for you guys. Thanks for the interest

**Comment by Kageetai** [comment]
Will close this now and consider it done, in lack of replies

**Comment by fzadow** [comment]
Thank you so much for implementing this. I tried it out the day you released it and forgot to reply. It works as expected and boosted the plugin's value immensely!

**Comment by Kageetai** [comment]
Glad to hear, this motivates me as well, of course :)
