### ISSUE TITLE
Releases 1.0.3 and 1.0.4 contain only source code

### ISSUE THREAD

**Issue by fzadow** [Kageetai/obsidian-plugin-journal-review#8]
your latest releases, 1.0.3 and 1.0.4, seem to be only the source code but not app.js etc.
is this by accident?
I couldn't install them directly through Obsidian (404)

**Comment by Kageetai** [comment]
Hey there, thanks for trying my plugin.
I hadn't updated in two months or so and already forgot the proper release process. I need to automate that :D
The proper files should be attached to the latest 1.0.4 release now

**Comment by Kageetai** [comment]
The release seems to have worked for others now, so I will close this for the time being. Feel free to comment again if someone is not working.
